### ISSUE TITLE
lacks of beauty and usability

### ISSUE THREAD

**Issue by zottce** [ZOTTCE/samp-sdk#15]
* The `define_native!` macro and a hand filled list of native functions. [Example 1](https://github.com/Sreyas-Sreelal/pawn-scraper/blob/master/src/plugin.rs#L45), [2](https://github.com/Sreyas-Sreelal/pawn-scraper/blob/master/src/plugin.rs#L96).
* No utility tools for variable numbers / types of arguments. [Example](https://github.com/Southclaws/pawn-templates/blob/master/src/plugin.rs#L79)
* Expensive string conversions in AMX <-> AMX scenarios. Something bmisiak is trying to fix. bmisiak/samp-sdk@349d0063129c0b923771911dc9d94571b07264ba

Post here any suggestions!

**Comment by zottce** [comment]
@Southclaws, @Sreyas-Sreelal would you like to comment or suggest something else? It's really hard for me to develop robust API right now. I hope your ideas would help me to finish the `rewriting` branch.

**Comment by Sreyas-Sreelal** [comment]
So glad to hear this!
I would love to see a safe async abstraction,as we discussed in pm,for implementing threaded functions more neatly and easily.

**Comment by Southclaws** [comment]
One thing I'd like to see with macros is a move towards macros-as-expressions so they can be used as return values - this is more idiomatic Rust and allows them to be more flexible. For example, instead of macros just declaring new variables by themselves, they should return rvalues so the call-site can declare their own variables. If they require intermediate variables, they should be scope-controlled.

Aside from this, I don't think this crate should balloon too big in scope. Keep it simple!

I think any other things, like async abstraction, should be done as separate crates. Just to keep things isolated and individually testable. One thing I wanted to write for pawn-requests was a callback bus, basically a small pub-sub system for easily setting up a callback call at any point in code from any thread without needing to manually set up an mpsc and capture in `process_tick`. This will likely be a separate crate from me soon.

But yes, I think this crate is 90% of the way there already, if you fix the three things you've listed here, it would be perfect ❤️ and then we can build additional functionality on top. Keep it simple!

**Comment by zottce** [comment]
@Southclaws,

I'm on my way to remove most of current macros (like `set_string`, `get_string`) and rewrite them as functions if needed.
`define_native`, `new_plugin`, `expand_args` will be procedural macros, which generates clearer code than current one. Most of generated code from current macros will be a part of the crate.

About keep this crate simple. Right now I have three crates: `samp-sdk`, just `samp` and `samp-codegen`.
 
`samp-sdk` has no more code generation and contains only AMX relative types (maybe even more than now, but they will be useful!) and bindings. I guess it will be useful to program some low-level stuff.

`samp-codegen` is proc-macro crate that has `#[native(name = "")]` attribute and `initialize_plugin!` macro.

`samp` reexports that crates to plugin developers and also includes information about a plugin like list of loaded AMXs, the pointer to list of exported AMX functions and some settings. It was previously generated by `new_plugin!` in the plugin crate.

I want it to be simple and clear to understand and maintain. Today I even cannot remember what most of macros do and why they exist.

What do you think?

**Comment by Southclaws** [comment]
That sounds perfect! I am looking forward to it. I would like to help where I can, perhaps with writing tests or providing examples.

Another request of mine would be to avoid nightly compiler features because it makes using the tooling very awkward (no linting works, vscode support doesn't work, CI sometimes won't work if the architecture hasn't received the latest update).

Thanks for your work on this project!
